apiVersion: apps/v1
kind: Deployment
metadata: 
  name: production-deploy
spec:
  replicas: 2
  selector: 
    matchLabels:
      env: production
  template:
    metadata:
      name: production-deploy-pod
      labels:
        env: production
    spec:
      containers:
      - name: production-deploy-cont
        image: piyush0927/jenkins_httpd:latest
